namespace CRD.Enums
{
    public enum StatusCode
    {
        SUCCESS,
        INCORRECT_USER_CREDENTIALS,
        ERROR,
        LOAN_ADDED,
        USER_DOES_MOT_HAVE_LOAN,
        LOAN_UPDATED,
        USER_DOES_NOT_EXIST,
        REGISTRATION_ERROR,
        LOAN_CANNOT_BE_UPDATED,
        USER_CANNOT_CHANGE_THIS_LOAN,
        PASSWORD_SHOULD_HAVE_AT_LEAST_8_CHARACTERS,
        PASSWORD_SHOULD_NOT_CONTAIN_SPACE,
        PASSWORD_SHOULD_CONTAIN_AT_LEAST_ONE_LOWER_AND_ONE_UPPER_CASE,
        LOAN_DOES_NOT_EXIST
    }
}

